Repository SUGAM-ARORA/Divinora, pull requests merged in 2025-04, with the labels that each got.

#130 added history timeline feature
  app/page.tsx
  package-lock.json
  package.json
Labels: pwoc, medium

#141 added multilingual support and printable ritual guides
  app/layout.tsx
  app/page.tsx
  components/GoogleTranslateWidget.tsx
Labels: pwoc, medium

#142 added perosnalized spiritual paths
  app/api/path-recommendation/route.ts
  app/page.tsx
  package-lock.json
  package.json
Labels: pwoc, hard

#143 Double Cross Resolved
  components/deity-modal.tsx
Labels: pwoc, easy

#144 Sanskrit Dictionary
  app/page.tsx
Labels: pwoc, medium
